// src/components/contact/contact.tsx
import {component$, type PropsOf } from '@builder.io/qwik';

import * as styles from './contact.styles';
import Channel from '../icons/channel';

export type ContactProperties = PropsOf<'a'> & {
	type: string;
	label: string;
	address: string;
};

export default component$<ContactProperties>(({ type, label, address, ...props}) => {
	return (
		<a class={styles.contact} href={address} rel="noopener" {...props}>
			<Channel class={styles.icon} type={type} />
			{label}
		</a>
	);
});

// src/components/Contact.vue
<script>
	import icons from '~/icons';

	export default {
		props: ['label', 'address', 'type'],
		computed: {
			icon: function() {
				return icons[this.type];
			},
		},
	};
</script>

<template>
	<a class="contact" :href="address" rel="noopener">
		<component :is="icon"/>
		{{ label }}
	</a>
</template>

<style lang="scss">
	.contact {
		font-size: 18px;

		svg {
			position: relative;
			top: -2px;

			display: inline-block;
			max-width: 18px;
			margin-right: 5px;

			vertical-align: middle;
		}
	}
</style>
