// src/components/project/project.tsx
import {component$, type PropsOf} from '@builder.io/qwik';
import Headline from '~/components/headline/headline';

import * as styles from './project.styles';

export type ProjectProperties = PropsOf<'article'> & {
	name: string;
	description?: string;
	address: string;
};

export default component$<ProjectProperties>(({ name, description, address, ...props }) => {
	return (
		<article class={styles.project} {...props}>
			<Headline class={styles.title} level={3}>
				<a href={address} rel="noopener">
					{name}
				</a>
			</Headline>

			{description && <p>{description}</p>}
		</article>
	);
});

// src/components/Project.vue
<script>
	export default {
		props: ['name', 'address', 'description'],
	};
</script>

<template>
	<article class="project">
		<h3 class="project__title">
			<a :href="address" rel="noopener">
				{{ name }}
			</a>
		</h3>

		<p class="project__description">
			{{ description }}
		</p>
	</article>
</template>

<style lang="scss">
	.project {
		margin-bottom: 24px;

		&__title {
			margin-bottom: 4px;
		}
	}
</style>
